export { default as DefaultVideoBox } from './translation/DefaultVideoBox'
export { default as VideoConnection } from './translation/VideoConnection'
export { default as VideoRecordBox } from './translation/VideoRecordBox'
export { default as VideoRecordControls } from './translation/VideoRecordControls'
export { default as VideoRecordSection } from './translation/VideoRecordSection'
export { default as VideoCard } from './translation/VideoCard'